enum VALIDATION_TYPE {
  SYSTEM_NAME,
  SYSTEM_ID,
  SYSTEM_TKCGR_NAME,
  SYSTEM_TKCGR_POS,
  SYSTEM_TKCGR_EMAIL,
  SYSTEM_IFGRP_NAME,
  SYSTEM_IFGRP_DOMAIN,
  SYSTEM_IFGRP_PORT,
}
export default VALIDATION_TYPE;
